version: "3.0"

services:
  backend:
    build: .
    container_name: backend
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mongo:latest
    container_name: db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
  swagger:
    build: ../KaiburrRestApplication
    container_name: swagger
    ports:
      - 6969:8080
    depends_on:
      - db


volumes:
  mongo:

